### PR TITLE
bug: cve exploiting malicious connection header

### LINKED ISSUE #188: Privilege escalation vulnerability via malicious "Connection" header
A user crafting an API request directed at `capsule-proxy` can get a privilege escalation using the Service Account of the proxy itself.

This is done by passing the `Impersonate-User` or `Impersonate-Group` header in the `Connection` header, using the same exploit described here: https://github.com/rancher/rancher/security/advisories/GHSA-pvxj-25m6-7vqr

> At this point, instead of impersonating the user and their permissions, the request will act as if it was from the ~~Rancher management server~~ Capsule Proxy and incorrectly return the information.

### PR DESCRIPTION
**Pull request by prometherion**
Closes #188.

We strongly suggest upgrading ASAP `capsule-proxy` to mitigate this CVE that doesn't have direct mitigation.

### CODE REVIEW

File: internal/webserver/webserver.go [hunk 1]
```diff
@@ -355,3 +358,27 @@ func (n kubeFilter) getProxyTenantsForOwnerKind(ownerKind capsulev1beta1.OwnerKi
...
+
+	connHeaders := request.Header.Values(headerName)
+
+	var sanitized []string
+
+	for _, values := range connHeaders {
+		parts := strings.Split(values, ",")
+
+		for _, part := range parts {
+			if strings.HasPrefix(strings.ToLower(part), "impersonate-") {
```
Comment (enj) [inline internal/webserver/webserver.go:373]: Instead of removing bad headers, I would suggest following the approach taken by https://github.com/traefik/traefik/pull/8319 to resolve https://github.com/traefik/traefik/security/advisories/GHSA-m697-4v8f-55qg - i.e. handle the connection header directly.

With `if strings.HasPrefix(strings.ToLower(part), "impersonate-") {` you miss edge cases such as (note the leading spaces):

```
curl "https://${API}/api/v1/secrets" -H "Authorization: Bearer ${TOKEN}" -H "Connection: foo, Impersonate-User, Impersonate-Group" -0
```

**Comment by enj** [comment]
@prometherion it would be great if a [GHSA](https://github.com/advisories) could be created once this fix is released.

File: internal/webserver/webserver.go (hunk 1 above)
Comment (prometherion) [reply internal/webserver/webserver.go]: Thanks for the hint!

File: internal/webserver/webserver.go [hunk 2]
```diff
@@ -355,3 +360,28 @@ func (n kubeFilter) getProxyTenantsForOwnerKind(ownerKind capsulev1beta1.OwnerKi
 
 	return
 }
+
+func (n *kubeFilter) removingHopByHopHeaders(request *http.Request) {
+	connectionHeaderName, upgradeHeaderName, requestUpgradeType := "connection", "upgrade", ""
```
Comment (enj) [inline internal/webserver/webserver.go:365]: These are case sensitive when used for direct header map access.

```suggestion
	connectionHeaderName, upgradeHeaderName, requestUpgradeType := "Connection", "Upgrade", ""
```

Comment (MaxFedotov) [reply internal/webserver/webserver.go:365]: Or use 'request.Header.Values[connectionHeaderName]'

Comment (prometherion) [reply internal/webserver/webserver.go:365]: Solved using the case-insensitive values retrieval function.

**Review by bsctl — APPROVED** [review]
lgtm thanks for the nice work

**Review by MaxFedotov — APPROVED** [review]
Lgtm!
